"""Build temporary import directory for Paperclip company import."""

from __future__ import annotations

import tempfile
from dataclasses import dataclass
from pathlib import Path

import yaml

from .agents_md_generator import generate_agents_md
from .hierarchy_reader import MergedAgent
from .yaml_generator import generate_paperclip_yaml


@dataclass
class ImportDirectory:
    """Result of building the import directory."""

    path: Path
    agent_count: int
    warnings: list[str]
    paperclip_yaml: dict  # raw dict for dry-run printing


def build_import_directory(
    agents: list[MergedAgent],
    repo_root: Path,
    company_name: str = "Ceremonia",
    company_slug: str = "ceremonia",
) -> ImportDirectory:
    """Build a temp directory containing .paperclip.yaml + agents/<key>/AGENTS.md.

    The temp directory is structured for `pnpm paperclipai company import`.

    Args:
        agents: List of merged agent specs.
        repo_root: Repository root directory.

    Returns:
        ImportDirectory with path, count, and any warnings.
    """
    temp_dir = Path(tempfile.mkdtemp(prefix="clawscaffold-paperclip-"))

    # Generate .paperclip.yaml
    paperclip_data = generate_paperclip_yaml(agents, repo_root=repo_root)
    paperclip_path = temp_dir / ".paperclip.yaml"
    paperclip_path.write_text(yaml.dump(paperclip_data, default_flow_style=False, sort_keys=False))

    # Generate agents/<key>/AGENTS.md
    warnings = generate_agents_md(agents, repo_root, temp_dir)

    # Generate COMPANY.md (required by Paperclip company import)
    company_path = temp_dir / "COMPANY.md"
    company_path.write_text(
        f'---\nname: "{company_name}"\nschema: "agentcompanies/v1"\nslug: "{company_slug}"\n---\n'
    )

    # Generate README.md
    readme_path = temp_dir / "README.md"
    readme_path.write_text(
        f"# Paperclip Import Directory\n\n"
        f"Generated by `clawscaffold sync-paperclip`.\n\n"
        f"- **Agents**: {len(agents)}\n"
        f"- **Source**: `{repo_root}`\n"
    )

    return ImportDirectory(
        path=temp_dir,
        agent_count=len(agents),
        warnings=warnings,
        paperclip_yaml=paperclip_data,
    )
