"""OpenProse adapter — generate .prose files for parallel stages."""

from __future__ import annotations

import re
from typing import Any


def _normalize_agent_label(agent: str) -> str:
    """Convert an agent id into a stable OpenProse label."""
    base = agent.removeprefix("agents-")
    label = re.sub(r"[^a-zA-Z0-9]+", "_", base).strip("_").lower()
    if not label:
        return "agent"
    if label[0].isdigit():
        return f"agent_{label}"
    return label


def generate_prose(stages: list[dict[str, Any]], pipeline_name: str) -> str:
    """Generate an OpenProse .prose file for parallel stage execution."""
    lines = [
        f"# Parallel stages for {pipeline_name}",
        "#",
        "# Generated by OpenClaw Scaffolder. Edit with care.",
        "",
    ]

    # Define agents from stages
    seen_agents: set[str] = set()
    agent_labels: dict[str, str] = {}
    used_labels: set[str] = set()
    for stage in stages:
        agent = stage.get("agent", "unknown")
        if agent in seen_agents or agent.startswith("script:") or agent == "human-gate" or agent == "unknown":
            continue
        seen_agents.add(agent)

        base_label = _normalize_agent_label(agent)
        agent_label = base_label
        counter = 2
        while agent_label in used_labels:
            agent_label = f"{base_label}_{counter}"
            counter += 1
        used_labels.add(agent_label)
        agent_labels[agent] = agent_label
        lines.extend([
            f"agent {agent_label}:",
            f"  model: sonnet",
            f'  prompt: "You are a specialist agent for the {pipeline_name} pipeline."',
            "",
        ])

    # Generate parallel block
    lines.append("parallel (on-fail: \"continue\"):")

    for stage in stages:
        agent = stage.get("agent", "unknown")
        if agent.startswith("script:") or agent == "human-gate" or agent == "unknown":
            continue

        agent_label = agent_labels[agent]
        task = stage.get("task", f"Execute {stage['id']} stage")

        lines.extend([
            f"  {stage['id']} = session: {agent_label}",
            f'    prompt: "{task}"',
        ])

    lines.extend([
        "",
        f'session "Summarize results from parallel stages"',
        "  context: { " + ", ".join(s["id"] for s in stages if not s.get("agent", "").startswith("script:") and s.get("agent") != "human-gate") + " }",
        "",
    ])

    return "\n".join(lines)
